all: CALCULADOREPICODETIEMPO GeneradorVectorDisordre SUPERMEGAGENERADORDEVECTORES CALCULADORADESORDEN

CALCULADOREPICODETIEMPO: CALCULADOREPICODETIEMPO.cc
	g++ -Wall -std=c++11 -O3 -D_GLIBCXX_DEBUG -o CALCULADOREPICODETIEMPO CALCULADOREPICODETIEMPO.cc

GeneradorVectorDisordre: GeneradorVectorDisordre.cc
	g++ -Wall -std=c++11 -O3 -D_GLIBCXX_DEBUG -o GeneradorVectorDisordre GeneradorVectorDisordre.cc

SUPERMEGAGENERADORDEVECTORES: SUPERMEGAGENERADORDEVECTORES.cc
	g++ -Wall -std=c++11 -O3 -D_GLIBCXX_DEBUG -o SUPERMEGAGENERADORDEVECTORES SUPERMEGAGENERADORDEVECTORES.cc

CALCULADORADESORDEN: CALCULADORADESORDEN.cc
	g++ -Wall -std=c++11 -O3 -D_GLIBCXX_DEBUG -o CALCULADORADESORDEN CALCULADORADESORDEN.cc

clean:
	rm -r SUPERMEGAGENERADORDEVECTORES GeneradorVectorDisordre CALCULADOREPICODETIEMPO CALCULADORADESORDEN